import {runtime} from './rule-store.ts';
import {SOURCES} from './tax.ts';
const GOVERNMENT_HOSTS=new Set(['www.incometaxindia.gov.in','incometaxindia.gov.in','www.incometax.gov.in','incometax.gov.in','egazette.gov.in','www.indiabudget.gov.in','indiabudget.gov.in','wmstatic-prd.incometaxindia.gov.in','traces61contents.tdscpc.gov.in']);
export function officialURL(url:string){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||!GOVERNMENT_HOSTS.has(u.hostname))throw Error('Only allowlisted Government of India sources are permitted.');return u;}
async function officialFetch(url:string){let target=officialURL(url);for(let i=0;i<4;i++){const r=await fetch(target,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(r.status>=300&&r.status<400){const location=r.headers.get('location');if(!location)throw Error('Missing redirect location');target=officialURL(new URL(location,target).href);continue;}if(!r.ok)throw Error(`Official source unavailable (${r.status})`);const reader=r.body?.getReader();if(!reader)throw Error('Official source was empty');let size=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>16*1024*1024){await reader.cancel();throw Error('Official source exceeds processing limit');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const b of chunks){bytes.set(b,offset);offset+=b.length;}if(size<100)throw Error('Official source was unexpectedly short');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(n=>n.toString(16).padStart(2,'0')).join('');return {url:target.href,hash,bytes:size};}throw Error('Too many redirects');}
export async function notifyAdmin(message:string){const e=runtime();if(!e.MAIL_API_KEY||!e.ADMIN_EMAIL||!e.MAIL_FROM)return 'pending: email credentials required';try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${e.MAIL_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:e.MAIL_FROM,to:[e.ADMIN_EMAIL],subject:'India Salary Tax: regulatory interpretation required',text:message}),signal:AbortSignal.timeout(10000)});return r.ok?'sent':`delivery failed (${r.status})`;}catch{return 'delivery failed';}}
export async function checkOfficialSources(){const db=runtime().DB;if(!db)throw Error('Monitoring database is unavailable.');const now=new Date().toISOString();const previous=await db.prepare('SELECT details FROM source_checks ORDER BY checked_at DESC LIMIT 1').first<{details:string}>();const prior=previous?JSON.parse(previous.details).sources:[];const sources:any[]=[];const urls=[SOURCES.act.url,SOURCES.finance.url,SOURCES.historical.url,'https://www.incometaxindia.gov.in/Pages/tax-services.aspx','https://www.incometaxindia.gov.in/finance-acts','https://egazette.gov.in/'];
for(const url of urls){try{const source=await officialFetch(url);const old=prior?.find((s:any)=>s.requestedURL===url);sources.push({...source,requestedURL:url,state:old?.hash===source.hash?'unchanged':old?.hash?'changed':'first fingerprint; interpretation baseline required'});}catch(error){sources.push({requestedURL:url,state:'unavailable',error:error instanceof Error?error.message:'Fetch failed'});}}
const uncertain=sources.some(s=>s.state!=='unchanged');const status=uncertain?'interpretation required':'unchanged';const message=uncertain?'Official sources changed, need an initial interpretation baseline, or could not be retrieved. Last verified effective rules continue. Review enacted legislation and its legal effective date; proposed measures must never activate.':'';const delivery=uncertain?await notifyAdmin(message):null;
const id=crypto.randomUUID();const statements=[db.prepare('INSERT INTO source_checks (id, checked_at, status, details) VALUES (?, ?, ?, ?)').bind(id,now,status,JSON.stringify({sources,message,policy:'Fingerprints detect changes; they do not interpret law. No automatic rule mutation occurs for uncertain changes.'}))];if(uncertain)statements.push(db.prepare('INSERT INTO alerts (id, created_at, message, delivery) VALUES (?, ?, ?, ?)').bind(crypto.randomUUID(),now,message,delivery));await db.batch(statements);return {id,checkedAt:now,status,sources,email:delivery};}
