import {SOURCES,micro,type Calculation} from './tax.ts';
const inr=(x:string)=>{const [w,f]=x.split('.');return 'INR '+BigInt(w).toLocaleString('en-IN')+(f?'.'+f:'');};
// Self-contained PDF 1.4 writer: no salary leaves the server and no report is stored.
export function report(c:Calculation){const lines:string[]=[`INDIA SALARY TAX | FY ${c.fy}-${String(c.fy+1).slice(-2)}`,'SALARY-ONLY / NEW TAX REGIME / RESIDENT INDIVIDUAL','',`Generated: ${c.generatedAt}`,`Rule version: ${c.rule.id}`,`Legal effective date: ${c.rule.effectiveFrom}`,`Official sources reviewed: ${c.rule.recordedAt}`,'','ANNUAL AND MONTHLY ESTIMATES',`Annual tax: ${inr(c.annualTax)}`,`Monthly tax (annual / 12): ${inr(c.monthlyTax)}`,`Post-tax annual income: ${inr(c.postTaxAnnual)}`,`Post-tax monthly income: ${inr(c.postTaxMonthly)}`,`Effective rate (total tax / gross salary): ${c.effectiveRate}%`,`Marginal rate (highest occupied slab, before cess / surcharge): ${c.marginalRate}%`,'','INCOME COMPUTATION',`Annual gross salary: ${inr(c.salary)}`,`Standard deduction: ${inr(c.deduction)} [${c.rule.refs.deduction}]`,`Income before rounding: ${inr(c.unroundedIncome)}`,`Income rounding adjustment: ${inr(c.incomeRounding)}`,`Taxable income after rounding: ${inr(c.income)} [${c.rule.refs.rounding}]`,'','SLAB-WISE TAX (BEFORE REBATE AND RELIEF)',c.rule.refs.slabs,...c.slabs.map(x=>`${inr(x.from)} to ${x.to?inr(x.to):'unlimited'} | ${x.rate}% | income ${inr(x.taxable)} | tax ${inr(x.tax)}`),'',`Slab tax total: ${inr(c.slabTax)}`,`Resident rebate: -${inr(c.rebate)} [${c.rule.refs.rebate}]`,`Rebate marginal relief: -${inr(c.rebateRelief)}`,`Income above rebate threshold: ${inr((BigInt(c.income)>BigInt(c.rule.rebateThreshold)?BigInt(c.income)-BigInt(c.rule.rebateThreshold):0n).toString())}`,`Tax after rebate and relief: ${inr(c.taxAfterRebate)}`,`Surcharge at ${c.surchargeRate}%: ${inr(c.surcharge)}`,`Surcharge marginal relief: -${inr(c.surchargeRelief)}`,c.rule.refs.surcharge,...(c.reliefThreshold?[`Threshold income: ${inr(c.reliefThreshold)}`,`Tax plus surcharge at threshold: ${inr(c.thresholdTax)}`,`Relief cap = threshold tax + excess income: ${inr(c.surchargeCap)}`]:[]),`Tax plus surcharge after relief: ${inr(c.preCess)}`,`Health & Education Cess at 4%: ${inr(c.cess)} [${c.rule.refs.cess}]`,`FINAL ANNUAL TAX (NO FINAL ROUNDING): ${inr(c.annualTax)}`,'','ASSUMPTIONS AND SCOPE',...c.assumptions,'','OFFICIAL-SOURCE TRACEABILITY',...c.rule.sources.flatMap(key=>{const s=SOURCES[key];return [s.title,s.locator,s.url,''];}),'Rules shown are enacted effective versions. Proposed rules are never used.','This estimate is not a filing determination. Conditional deductions require additional facts.'];
const ascii=(s:string)=>s.replace(/₹/g,'INR ').replace(/[–—]/g,'-').replace(/[^\x20-\x7e]/g,'');
const wrapped=lines.flatMap(line=>{const s=ascii(line);if(!s)return [''];const result:string[]=[];let remaining=s;while(remaining.length>82){let split=remaining.lastIndexOf(' ',82);if(split<20)split=82;result.push(remaining.slice(0,split));remaining=remaining.slice(split).trimStart();}result.push(remaining);return result;});
const pages:string[][]=[];for(let i=0;i<wrapped.length;i+=49)pages.push(wrapped.slice(i,i+49));
// A separate vector chart page makes the gross contribution of each slab explicit.
const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const streams=pages.map((page,i)=>`0.067 0.094 0.153 rg\nBT /F1 10 Tf 42 796 Td 14 TL\n${page.map((line,j)=>`${j?'T* ':''}(${escape(line)}) Tj`).join('\n')}\nET\nBT /F1 9 Tf 42 30 Td (India Salary Tax | ${c.rule.id} | Page ${i+1}) Tj ET`);
let chart='0.067 0.094 0.153 rg BT /F1 18 Tf 42 785 Td (Tax contribution by slab) Tj ET\nBT /F1 10 Tf 42 756 Td (Gross slab tax, before rebate, relief, surcharge and cess) Tj ET\n';const maxTax=c.slabs.reduce((m,s)=>{const n=micro(s.tax);return n>m?n:m;},1n);c.slabs.forEach((slab,i)=>{const y=710-i*65;const width=Number(micro(slab.tax)*33000n/maxTax)/100;chart+=`0.067 0.094 0.153 rg BT /F1 10 Tf 42 ${y+20} Td (Slab ${i+1} | ${slab.rate}% | contribution shown in slab table) Tj ET\n0.129 0.404 0.933 rg 42 ${y} ${width.toFixed(2)} 10 re f\n`;});chart+='0.067 0.094 0.153 rg BT /F1 10 Tf 42 180 Td (See calculation pages for exact amounts and statutory adjustments.) Tj ET';streams.push(chart);
const objects:string[]=['',''];const fontId=3;objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const kids:number[]=[];streams.forEach(stream=>{const id=objects.length+1;const contentId=id+1;kids.push(id);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);});objects[0]='<< /Type /Catalog /Pages 2 0 R >>';objects[1]=`<< /Type /Pages /Count ${kids.length} /Kids [${kids.map(n=>`${n} 0 R`).join(' ')}] >>`;let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((object,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${object}\nendobj\n`;});const start=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>n.toString().padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return new TextEncoder().encode(pdf);}
