import { environment } from './storage.ts';
import { RULES, currentFY, CHECKED, type Rule } from './tax.ts';
export function runtime(){return environment;}

export async function allRules():Promise<Rule[]>{const db=runtime().DB;if(!db)return RULES;const rows=await db.prepare('SELECT payload FROM rule_versions ORDER BY recorded_at').all<{payload:string}>();return [...RULES,...rows.results.map(r=>JSON.parse(r.payload) as Rule)];}
export async function selectRule(fy:number,now=new Date()){const rules=await allRules();const day=now.toISOString().slice(0,10);const candidates=rules.filter(r=>r.fy===fy&&r.status==='enacted'&&r.effectiveFrom<=day).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom)||a.recordedAt.localeCompare(b.recordedAt));const rule=candidates.at(-1);if(!rule)throw Error('No verified effective rule is available for this FY.');return rule;}
export async function publicRules(){const years=[...new Set((await allRules()).filter(r=>r.fy<=currentFY()&&r.effectiveFrom<=new Date().toISOString().slice(0,10)).map(r=>r.fy))].sort((a,b)=>a-b);const result=await Promise.all(years.map(fy=>selectRule(fy)));return {rules:result,currentFY:currentFY(),lastVerified:CHECKED};}
export async function monitoring(){const env=runtime(),rules=await allRules(),db=env.DB;const checks=db?(await db.prepare('SELECT * FROM source_checks ORDER BY checked_at DESC LIMIT 36').all()).results:[];const alerts=db?(await db.prepare('SELECT * FROM alerts ORDER BY created_at DESC LIMIT 50').all()).results:[];return {rules,active:await selectRule(Math.max(...rules.filter(r=>r.fy<=currentFY()&&r.effectiveFrom<=new Date().toISOString().slice(0,10)).map(r=>r.fy))),lastVerified:CHECKED,lastChecked:(checks[0] as any)?.checked_at??null,checks,alerts,integration:{database:!!db,scheduler:'External monthly scheduler required',email:!!(env.MAIL_API_KEY&&env.ADMIN_EMAIL&&env.MAIL_FROM),interpreter:'Validated official-document adapter required; ambiguous changes never activate'},policy:'Read-only rules. Proposed legislation never activates. Enacted, confidently interpreted versions activate only on their legal effective date.'};}

