export const CHECKED = '2026-10-01';
export const SOURCES = {
 historical:{title:'Income-tax Act, 1961: Section 115BAC',url:'https://www.incometaxindia.gov.in/w/section-115bac-7',locator:'115BAC(1), (1A)(i)–(iii); historical slab tables and effective assessment years'},
 early:{title:'TRACES: FY 2021–22 New Regime',url:'https://traces61contents.tdscpc.gov.in/en/incometax-2021-2022-new.html',locator:'Slab table; surcharge 10%, 15%, 25%, 37%; 4% cess'},
 salary:{title:'Income Tax Department: salaried individuals',url:'https://www.incometax.gov.in/iec/foportal/help/individual/return-applicable-1',locator:'AY 2026–27: slabs, rebate, surcharge, marginal relief and cess'},
 act:{title:'Income-tax Act, 2025, amended by Finance Act, 2026',url:'https://www.incometaxindia.gov.in/documents/d/guest/income_tax_act_2025_as_amended_by_fa_act_2026-pdf',locator:'Sections 19(1) Table item 2, 156(2), 202(1), 516; rebate PDF pp.216–217; rounding p.576'},
 finance:{title:'Finance Act, 2026 — enacted 30 March 2026',url:'https://www.incometaxindia.gov.in/documents/d/guest/finance-act-2026-pdf-1',locator:'Section 3(4)(b) Table item 10; 3(5) Table item 6; 3(16); effective 1 April 2026'},
 deduction:{title:'CBDT validation rules, AY 2025–26',url:'https://www.incometax.gov.in/iec/foportal/sites/default/files/2025-07/CBDT_e-Filing_ITR%204_Validation%20Rules_AY%202025-26_V1.1.pdf',locator:'Rule 279: ₹75,000 standard deduction under the New Regime'},
 rebate:{title:'Income Tax Department: tax rates by year',url:'https://wmstatic-prd.incometaxindia.gov.in/documents/20117/42998/Tax-rates%E2%80%8B_2026-01-22_11-20-48_540e32_en.pdf/021c2f6a-881c-f666-3449-ccf0bcc172b8?download=true&t=1775401209128&version=1.0',locator:'Section 87A: ₹12,500 / ₹25,000 / ₹60,000 rebates and marginal relief by AY'}
};
export type Rule={id:string;fy:number;effectiveFrom:string;recordedAt:string;status:'enacted';standardDeduction:string;rebateThreshold:string;rebateMax:string;rebateRelief:boolean;slabs:[string|null,number][];surcharges:[string,number][];refs:{slabs:string;deduction:string;rebate:string;surcharge:string;rounding:string;cess:string};sources:(keyof typeof SOURCES)[]};
const old:[string|null,number][]=[['250000',0],['500000',5],['750000',10],['1000000',15],['1250000',20],['1500000',25],[null,30]];
const r23:[string|null,number][]=[['300000',0],['600000',5],['900000',10],['1200000',15],['1500000',20],[null,30]];
const r24:[string|null,number][]=[['300000',0],['700000',5],['1000000',10],['1200000',15],['1500000',20],[null,30]];
const latest:[string|null,number][]=[['400000',0],['800000',5],['1200000',10],['1600000',15],['2000000',20],['2400000',25],[null,30]];
export const RULES:Rule[]=Array.from({length:7},(_,i)=>{const fy=2020+i;return {id:`IN-NR-SAL-${fy}-v1`,fy,effectiveFrom:`${fy}-04-01`,recordedAt:CHECKED,status:'enacted',standardDeduction:fy<2023?'0':fy===2023?'50000':'75000',rebateThreshold:fy<2023?'500000':fy<2025?'700000':'1200000',rebateMax:fy<2023?'12500':fy<2025?'25000':'60000',rebateRelief:fy>=2023,slabs:fy<2023?old:fy===2023?r23:fy===2024?r24:latest,surcharges:fy<2023?[['5000000',10],['10000000',15],['20000000',25],['50000000',37]]:[['5000000',10],['10000000',15],['20000000',25]],refs:{slabs:fy>=2026?'Section 202(1), Income-tax Act, 2025':fy<2023?'Section 115BAC(1), Income-tax Act, 1961':`Section 115BAC(1A)(${fy===2023?'i':fy===2024?'ii':'iii'}), Income-tax Act, 1961`,deduction:fy>=2026?'Section 19(1), Table item 2':fy<2023?'Section 115BAC(2): standard deduction unavailable':'Section 16(ia) read with 115BAC',rebate:fy>=2026?'Section 156(2), Income-tax Act, 2025 (successor to 87A)':'Section 87A, Income-tax Act, 1961',surcharge:fy>=2026?'Finance Act, 2026, 3(4)(b) item 10 and 3(5) item 6':`Finance Act ${fy}, Section 2 and First Schedule: surcharge and marginal relief`,rounding:fy>=2026?'Section 516, Income-tax Act, 2025':'Sections 288A and 288B, Income-tax Act, 1961',cess:fy>=2026?'Finance Act, 2026, Section 3(16)':`Finance Act ${fy}, Section 2: Health & Education Cess`},sources:fy>=2026?['act','finance']:fy>=2025?['historical','salary','rebate']:fy>=2024?['historical','deduction','rebate']:fy>=2023?['historical','rebate']:['historical','early','rebate']};});
const S=1000000n;
const min=(a:bigint,b:bigint)=>a<b?a:b;
const max=(a:bigint,b:bigint)=>a>b?a:b;
export function roundedIncome(n:bigint){return ((n+5n)/10n)*10n;}
function decimal(n:bigint){const sign=n<0n?'-':'';n=n<0n?-n:n;const fraction=(n%S).toString().padStart(6,'0').replace(/0+$/,'');return sign+(n/S).toString()+(fraction?'.'+fraction:'');}
function monthly(n:bigint){const cents=(n*100n+6n*S)/(12n*S);return `${cents/100n}.${(cents%100n).toString().padStart(2,'0')}`;}
function base(income:bigint,r:Rule){let floor=0n;return r.slabs.map(([cap,rate])=>{const end=cap===null?income:BigInt(cap);const taxable=max(0n,min(income,end)-floor);const row={from:floor.toString(),to:cap,rate,taxable:taxable.toString(),tax:decimal(taxable*BigInt(rate)*S/100n)};floor=end;return row;});}
function baseTax(income:bigint,r:Rule){return base(income,r).reduce((n,x)=>n+micro(x.tax),0n);}
export function micro(x:string){const [a,b='']=x.split('.');return BigInt(a)*S+BigInt(b.padEnd(6,'0'));}
function surchargeRate(income:bigint,r:Rule){return r.surcharges.reduce((rate,[threshold,next])=>income>BigInt(threshold)?next:rate,0);}
export function currentFY(now=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'numeric'}).formatToParts(now);const year=Number(parts.find(x=>x.type==='year')!.value);const month=Number(parts.find(x=>x.type==='month')!.value);return year-(month<4?1:0);}
export function validateInput(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Enter a salary and financial year.');const x=input as Record<string,unknown>;if(Object.keys(x).some(k=>!['salary','fy'].includes(k)))throw Error('Only annual salary and financial year are accepted.');if(typeof x.salary!=='string'||!/^\d+$/.test(x.salary))throw Error('Salary must be a non-negative whole-rupee string.');if(!Number.isInteger(x.fy)||Number(x.fy)<2020||Number(x.fy)>currentFY())throw Error('Choose a current or past FY from 2020–21 onward.');return {salary:x.salary,fy:Number(x.fy)};}
export function calculate(salary:string,rule:Rule){const gross=BigInt(salary),deduction=min(gross,BigInt(rule.standardDeduction)),unrounded=gross-deduction,income=roundedIncome(unrounded),slabs=base(income,rule),tax=baseTax(income,rule),threshold=BigInt(rule.rebateThreshold);let rebate=0n,rebateRelief=0n;if(income<=threshold)rebate=min(tax,BigInt(rule.rebateMax)*S);else if(rule.rebateRelief)rebateRelief=max(0n,tax-(income-threshold)*S);const net=tax-rebate-rebateRelief,rate=surchargeRate(income,rule),surcharge=net*BigInt(rate)/100n;let surchargeRelief=0n,reliefThreshold: string|null=null,thresholdTax=0n,cap=0n;const crossed=rule.surcharges.filter(([t])=>income>BigInt(t));if(crossed.length){reliefThreshold=crossed.at(-1)![0];const t=BigInt(reliefThreshold);thresholdTax=baseTax(t,rule)*(100n+BigInt(surchargeRate(t,rule)))/100n;cap=thresholdTax+(income-t)*S;surchargeRelief=max(0n,net+surcharge-cap);}
const preCess=net+surcharge-surchargeRelief,cess=preCess*4n/100n,annual=preCess+cess,post=gross*S-annual;const marginal=slabs.filter(x=>BigInt(x.taxable)>0n).at(-1)?.rate??0;const pct=gross===0n?0n:(annual*10000n+gross*S/2n)/(gross*S);const effective=`${pct/100n}.${(pct%100n).toString().padStart(2,'0')}`;
return {fy:rule.fy,rule,generatedAt:new Date().toISOString(),salary:gross.toString(),deduction:deduction.toString(),unroundedIncome:unrounded.toString(),income:income.toString(),incomeRounding:(income-unrounded).toString(),slabs,slabTax:decimal(tax),rebate:decimal(rebate),rebateRelief:decimal(rebateRelief),taxAfterRebate:decimal(net),surchargeRate:rate,surcharge:decimal(surcharge),surchargeRelief:decimal(surchargeRelief),reliefThreshold,thresholdTax:decimal(thresholdTax),surchargeCap:decimal(cap),preCess:decimal(preCess),cess:decimal(cess),annualTax:decimal(annual),monthlyTax:monthly(annual),effectiveRate:effective,marginalRate:marginal,postTaxAnnual:decimal(post),postTaxMonthly:monthly(post),assumptions:['Resident individual; salary income only; New Tax Regime.','Gross salary is taxable salary before standard deduction, not CTC.','Only deductions identifiable from salary alone are applied. Employer NPS, Agniveer contributions, exempt allowances and arrears relief need facts outside this one-input scope.','Post-tax income is salary less income tax; EPF, professional tax and other payroll deductions are excluded.','Final annual tax is shown exactly without final-tax rounding. Taxable-income rounding remains applied.','Monthly values are annual estimates divided by 12, displayed to two decimal places, not a TDS schedule.']};}
export type Calculation=ReturnType<typeof calculate>;
